
[colors.bright]
black = "0x2e3436"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x73d216"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xedd400"

[colors.primary]
foreground = "0xeeeeec"

[cursor.style]
# 光标形状
#   - ▇ Block
#   - _ Underline
#   - | Beam
blinking = "Always"
shape = "Underline"

# 字体设置为等宽字体，可以用命令 fc-list 查看你系统的字体
[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[window]
# 背景半透明，方便抄代码
opacity = 0.75

[window.dimensions]
# 窗口大小
columns = 90
lines = 27

[general]
# 实时重载配置文件，不用重启测试配置选项
live_config_reload = true


